openapi: 3.0.0
info:
  title: Recipes API
  description: Application which allows users to manage their favourite recipes.
  version: 0.0.1
servers:
  - url: https://sayagain.app/api
    description: Main (production) server
  - url: http://localhost:8002/sayagain/api
    description: Localhost (dev) server
paths:
  /recipes:
    get:
      summary: Get recipes
      operationId: getRecipes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Recipe'
  /recipes/search:
    post:
      summary: Get filtered recipes
      operationId: getFilteredRecipes
      requestBody:
        description: Search criteria
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchCriteria'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Recipe'
components:
  schemas:
    Ingredient:
      title: Ingredient
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Recipe:
      title: Recipe
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        servings:
          type: integer
        vegetarian:
          type: boolean
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
    SearchCriteria:
      title: SearchCriteria
      type: object
      properties:
        servings:
          type: integer
        vegetarian:
          type: boolean
        includeIngredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        excludeIngredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        fullTextQuery:
          type: string